### ISSUE TITLE
Git error: could not find repository from '/Users/vagrant/git'

### ISSUE THREAD

**Issue by robabbott** [Holdapp/bitrise-step-jira-build#13]
After setting up the step with required variables, it seems I am unable to connect to `Git`.  It might be stemming from the `libgit2` cask, which it seems to have trouble loading initially?  This is the only step in my workflow.  I have Git successfully connected to my Bitrise app and am already running automated builds that stem from GitHub pushes.

I am running this on a Mac with: **Xcode 13.0.x, macOS 12.4 (Monterey)**

**Full output below:**
+------------------------------------------------------------------------------+
| (1) jira-issue-update-build@0                                                |
+------------------------------------------------------------------------------+
| id: jira-issue-update-build                                                  |
| version: 0.2.4                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2022-11-16T16:45:25Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[16:45:25]  * [OK] Step dependency (pkg-config) installed, available. 
INFO[16:45:25]  * [OK] Step dependency (go) installed, available. 
+++ dirname /var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/bitrise4036651634/step_src/step.sh
++ cd /var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/bitrise4036651634/step_src
++ pwd
+ THIS_SCRIPT_DIR=/var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/bitrise4036651634/step_src
++ uname -s
+ '[' Darwin == Linux ']'
++ uname -s
+ '[' Darwin == Darwin ']'
+ FORMULA_COMMIT_HASH=54b426b84c8824ae457ae7f654670cc6c30bf46f
+ FORMULA_PATH=/var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/bitrise4036651634/step_src/libgit2.rb
+ curl https://raw.githubusercontent.com/Homebrew/homebrew-core/54b426b84c8824ae457ae7f654670cc6c30bf46f/Formula/libgit2.rb -o /var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/bitrise4036651634/step_src/libgit2.rb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2262  100  2262    0     0  15721      0 --:--:-- --:--:-- --:--:-- 16273
+ HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
+ HOMEBREW_NO_AUTO_UPDATE=1
+ brew install /var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/bitrise4036651634/step_src/libgit2.rb
Error: Failed to load cask: /var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/bitrise4036651634/step_src/libgit2.rb
Cask 'libgit2' is unreadable: wrong constant name #<Class:0x00007f9ada970758>
Warning: Treating /var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/bitrise4036651634/step_src/libgit2.rb as a formula.
==> Downloading https://ghcr.io/v2/homebrew/core/libgit2/manifests/1.3.0
==> Downloading https://ghcr.io/v2/homebrew/core/libgit2/blobs/sha256:426cbbe5464b73d9255f1ae3cccba1a241245b81203ac28e36b428bbd6bb32b8
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:426cbbe5464b73d9255f1ae3cccba1a241245b81203ac28e36b428bbd6bb32b8?se=2022-11-16T16%3A55%3A00Z&sig=%2Fski%2FFAiZB0xaItG0anewfcc8ju4Iivs3%2BjJyssbdPU%3D&sp=r&spr=https&sr=b&sv=2019-12-12
Warning: libgit2 1.5.0 is available and more recent than version 1.3.0.
==> Pouring libgit2--1.3.0.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/libgit2/1.3.0: 102 files, 3.4MB
Warning: HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK is set: not checking for outdated
dependents or dependents with broken linkage!
++ mktemp -d
+ TMP_GOPATH_DIR=/var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/tmp.hUlRLtHj
+ GO_PACKAGE_NAME=github.com/Holdapp/bitrise-step-jira-build
+ FULL_PACKAGE_PATH=/var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/tmp.hUlRLtHj/src/github.com/Holdapp/bitrise-step-jira-build
+ mkdir -p /var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/tmp.hUlRLtHj/src/github.com/Holdapp/bitrise-step-jira-build
+ rsync -avh --quiet /var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/bitrise4036651634/step_src/ /var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/tmp.hUlRLtHj/src/github.com/Holdapp/bitrise-step-jira-build/
+ export GOPATH=/var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/tmp.hUlRLtHj
+ GOPATH=/var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/tmp.hUlRLtHj
+ go run /var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/tmp.hUlRLtHj/src/github.com/Holdapp/bitrise-step-jira-build/main.go
# github.com/Holdapp/bitrise-step-jira-build/vendor/github.com/libgit2/git2go/v33
ld: warning: dylib (/usr/local/Cellar/libgit2/1.3.0/lib/libgit2.dylib) was built for newer macOS version (12.0) than being linked (11.3)
# command-line-arguments
ld: warning: object file (/var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/go-link-1871434766/000049.o) was built for newer macOS version (12.0) than being linked (11.3)
ld: warning: object file (/var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/go-link-1871434766/000050.o) was built for newer macOS version (12.0) than being linked (11.3)
ld: warning: object file (/var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/go-link-1871434766/000051.o) was built for newer macOS version (12.0) than being linked (11.3)
ld: warning: object file (/var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/go-link-1871434766/000052.o) was built for newer macOS version (12.0) than being linked (11.3)
ld: warning: object file (/var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/go-link-1871434766/000053.o) was built for newer macOS version (12.0) than being linked (11.3)
ld: warning: object file (/var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/go-link-1871434766/000054.o) was built for newer macOS version (12.0) than being linked (11.3)
ld: warning: object file (/var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/go-link-1871434766/000055.o) was built for newer macOS version (12.0) than being linked (11.3)
ld: warning: object file (/var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/go-link-1871434766/000056.o) was built for newer macOS version (12.0) than being linked (11.3)
ld: warning: object file (/var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/go-link-1871434766/000057.o) was built for newer macOS version (12.0) than being linked (11.3)
ld: warning: object file (/var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/go-link-1871434766/000058.o) was built for newer macOS version (12.0) than being linked (11.3)
ld: warning: object file (/var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/go-link-1871434766/000059.o) was built for newer macOS version (12.0) than being linked (11.3)
ld: warning: object file (/var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/go-link-1871434766/000060.o) was built for newer macOS version (12.0) than being linked (11.3)
ld: warning: object file (/var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/go-link-1871434766/000061.o) was built for newer macOS version (12.0) than being linked (11.3)
ld: warning: object file (/var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/go-link-1871434766/000062.o) was built for newer macOS version (12.0) than being linked (11.3)
ld: warning: dylib (/usr/local/Cellar/libgit2/1.3.0/lib/libgit2.dylib) was built for newer macOS version (12.0) than being linked (11.3)
Scanning Bitrise API for previous failed/aborted builds
Scanning git repo for JIRA issues (1 anchor[s])
Git error: could not find repository from '/Users/vagrant/git'

**Comment by fredyshox** [comment]
It seems like despite linker warnings, the steps launches properly, but it cannot access git repository.

> This is the only step in my workflow.

Maybe thats the problem, do you clone repository in your workflow before running this step (for example, using: https://www.bitrise.io/integrations/steps/git-clone)?

**Comment by robabbott** [comment]
@fredyshox Thanks for the quick response!  That seems to have resolved the issue.  Didn't realize I had to clone the repo during the workflow - the code in the step seemed like it might be able to manage that connection using the Bitrise environment secrets.  Is this how the step is meant to function?  Might be helpful to others to add that to the step description / instructions?  Thanks again 😄

**Comment by fredyshox** [comment]
> Is this how the step is meant to function?

Yes, it does work by analyzing project repository located at `$BITRISE_SOURCE_DIR` (path, where bitrise stores cloned repo when using `git-clone`), which in most cases is already cloned (for example in build workflows).

> Might be helpful to others to add that to the step description / instructions

If thats helpful, I will mention this in step description in the next release 🙂

**Comment by fredyshox** [comment]
Added in a35a437. Will be available as a part of 0.2.5 release.
