### ISSUE TITLE
Incompatible libgit2 and git2go versions

### ISSUE THREAD

**Issue by Abbeyy** [Holdapp/bitrise-step-jira-build#8]
## Pipeline Output
`[36mINFO[0m[13:13:58]  * [32;1m[OK][0m Step dependency (pkg-config) installed, available. 
[34;1m(libgit2) isn't installed, installing...[0m
[34;1m * [32;1m[OK][0m libgit2 installed[0m
[36mINFO[0m[13:14:06]  * [32;1m[OK][0m Step dependency (libgit2) installed, available. 
[36mINFO[0m[13:14:06]  * [32;1m[OK][0m Step dependency (go) installed, available. 
              dirname /var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/bitrise1234391084/step_src/step.sh
         cd /var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/bitrise1234391084/step_src
         pwd
    THIS_SCRIPT_DIR=/var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/bitrise1234391084/step_src
         uname -s
         '[' Darwin == Linux ']'
         mktemp -d
    TMP_GOPATH_DIR=/var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/tmp.z31mef7z
     GO_PACKAGE_NAME=github.com/Holdapp/bitrise-step-jira-build
    FULL_PACKAGE_PATH=/var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/tmp.z31mef7z/src/github.com/Holdapp/bitrise-step-jira-build
     mkdir -p /var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/tmp.z31mef7z/src/github.com/Holdapp/bitrise-step-jira-build
    rsync -avh --quiet /var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/bitrise1234391084/step_src/ /var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/tmp.z31mef7z/src/github.com/Holdapp/bitrise-step-jira-build/
    export GOPATH=/var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/tmp.z31mef7z
    GOPATH=/var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/tmp.z31mef7z
    go run /var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/tmp.z31mef7z/src/github.com/Holdapp/bitrise-step-jira-build/main.go
github.com/Holdapp/bitrise-step-jira-build/vendor/github.com/libgit2/git2go/v30
/var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/tmp.z31mef7z/src/github.com/Holdapp/bitrise-step-jira-build/vendor/github.com/libgit2/git2go/v30/Build_system_dynamic.go:11:3: error: "Invalid libgit2 version; this git2go supports libgit2 between v1.0.0 and v1.1.0".
error "Invalid libgit2 version; this git2go supports libgit2 between v1.0.0 and v1.1.0".`

## Issue
The error complains that the `libgit2` version installed is not compatible with `git2go`'s version. 

I can see recent releases this year that appear to be for the same reason so hopefully it's not too much work :) Thank you!

(Please forgive any formatting issues - 1st time issue poster!)

**Comment by fredyshox** [comment]
Hi, are you using step from bitrise library or pulling latest version from git? 

The one in step library is outdated, I will try to publish new version there soon. 
As for now, you can pull the latest version from git, by replacing the `jira-issue-update-build@0` with
`git::https://github.com/Holdapp/bitrise-step-jira-build.git@0.2.2` in workflow's bitrise.yml file

**Comment by fredyshox** [comment]
New version of this step (0.2.3) has been sent to review: https://github.com/bitrise-io/bitrise-steplib/pull/3622

**Comment by fredyshox** [comment]
Step has just been merged to steplib.
